theme: jekyll-theme-minimal
title: Raspberry Pi 5 as a home server
description: Raspberry Pi 5 configuration as home server (gateway, NAS, ...)
sidebar:
  - index
  - hardware
  - operating-system
  - disk-encryption
  - network
  - fw
  - dhcp-dns